PRAGMA foreign_keys = ON;

CREATE TABLE Events (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	date INTEGER NOT NULL,
	Title TEXT,
	Description TEXT,
	Author text
);

CREATE TABLE Tags_list (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Tag TEXT NOT NULL UNIQUE
);

CREATE TABLE Tags_of_events (
	Event_id INTEGER NOT NULL,
	Tag_id INTEGER NOT NULL,
	FOREIGN KEY(Event_id)
		REFERENCES Events(Id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(Tag_id)
		REFERENCES Tags_list(Id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

CREATE TABLE Tags_tree (
	Id INTEGER UNIQUE NOT NULL,
	Parent_id INTEGER CHECK (Parent_id != Id),
	FOREIGN KEY(Id)
		REFERENCES Tags_list(Id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
	FOREIGN KEY(Parent_id)
		REFERENCES Tags_list(Id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

CREATE TABLE Attachments (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Event_id INTEGER NOT NULL,
	Name TEXT NOT NULL,
	Type TEXT,
	File_name TEXT NOT NULL,
	FOREIGN KEY(Event_id)
		REFERENCES Events(Id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

INSERT INTO Tags_list VALUES (null, '-');
INSERT INTO Tags_tree SELECT Id, null FROM Tags_list WHERE Tag = '-';
